# Use the Python 3 base image
FROM python:3

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the app code into the container
COPY . /app

# Set the command to run the application
CMD ["python", "app.py"]
